<?php

/**
 * @file
 * Contains unl_contact.module.
 */

use Drupal\Core\Form\ConfigFormBase;

/**
 * Implements hook_form_alter().
 */
function unl_contact_form_alter(&$form, $form_state, $form_id) {
  // Look for any form provided by the contact module.
  // If you want to target a specific form you'll use the whole form ID
  // (e.g. Website feedback = 'contact_message_feedback_form').
  if (strpos($form_id, 'contact_message_') !== FALSE) {
     
    $config = \Drupal::config('unl_contact.settings');
    $show_map = \Drupal::config('unl_contact.settings')->get('unl_contact.show_map');
    $prefix = '<section class="contact-page">
        <div class="contact-wr">
            <div class="contact-info">
                <div class="contact-detail">
                    <h2>'. t('Our contact details') .'</h2>
                    <a href="tel:' . $config->get('unl_contact.contact_phone') . '">'
                    . $config->get('unl_contact.contact_phone') . '</a>
                    <a href="mailto:' . $config->get('unl_contact.contact_email') . '">'
                    . $config->get('unl_contact.contact_email') . '</a>
                </div>';
    if($show_map){
      $prefix .= '<div class="contact-location">
          <h2>Where are we?</h2>

          <div class="map" id="map"></div>
      </div>';
    }
    //          <p>adress adress adress adress</p>

    $prefix .='</div><div class="contact-form">';
    $form['#prefix'] = $prefix;
    $form['#suffix'] = '</div></div>
    </section>';
    $form['actions']['preview']['#access'] = FALSE;
    foreach($form['#attributes']['class'] as $key => $form_class) {
      if($form_class == 'contact-form'){
        unset($form['#attributes']['class'][$key]);
      }
    }

    $form['#attributes']['class'][] = 'contact-us-form';
    $form['title'] = [
      '#markup' => '<h2>' . t('Contact us') . '</h2>',
      '#weight' => -10,
    ];
    $form['term_info'] = [
      '#markup' => '<p class="term-info">' . t('By clicking Send you accept our <a target="_blank" href="/node/45">terms and conditions</a>') . '</p>',
      '#weight' => 10,
    ];
    $form['name']['#attributes']['class'][] = 'form-item';
    $form['name']['#title'] = t('Name');
    $form['mail']['#title'] = t('Email address');

    $form['field_phone']['#attributes']['class'][] = 'form-item';

    $default_action = \Drupal::request()->query->get('label');
    $default_name = \Drupal::request()->query->get('name');

    $form['subject']['widget'][0]['value']['#default_value']['#default_value'] = $default_action . ' ' . $default_name;
    $form['subject']['#attributes']['class'][] = 'form-item';

    $form['mail']['#attributes']['class'][] = 'form-item';
    $form['message']['#attributes']['class'][] = 'form-item';
    
    
    $form['actions']['submit']['#attributes']['class'][] = 'btn';
    $form['actions']['submit']['#attributes']['class'][] = \Drupal::service('language_manager')->getCurrentLanguage()->getId();
    
    $form['actions']['submit']['#value'] = '';

    $form['#attached']['library'][] = 'unl_contact/unl_contact.google_maps';
  }
}
